theme: jekyll-theme-cayman
title: Diego Castro Viadero
description: Curriculum Vitae
show_downloads: false
github:
  is_project_page: false
linkedin:
  public_profile_url: https://www.linkedin.com/in/diego-castro-viadero-9192a278